### ISSUE TITLE
Can I remove geometric nonlinearities?

### ISSUE THREAD

**Issue by Giannis1993** [adtzlr/trusspy#16]
My question is whether I can choose whether to include geometric nonlinearities (as one can do with material nonlinearities).

**Comment by adtzlr** [comment]
Short answer: No. 

This will **never** be implemented as TrussPy is intended as a nonlinear analysis program and the whole power of the solution algorithm (path-following) is based on an exact geometric description of the system kinematics.

**Comment by Giannis1993** [comment]
I thought that if you put the step-wise solution parameters as follows, you can only use the initial tangent stiffness and therefore obtain the linear solution:


# Step-wise solution parameters
M.Settings.dlpf = 1         # maximum allowed incremental load-proportionality-factor
M.Settings.du = 10000       # maximum allowed incremental displacement component (a large number)
M.Settings.incs = 1         # maximum number of increments

Anyway, thanks a lot for the code. Very helpul!
