### ISSUE TITLE
No such file or directory: 'pandoc'

### ISSUE THREAD

**Issue by aaronsxzhao** [adtzlr/trusspy#28]
Python version: `3.11`
Trusspy Version: [`trusspy 20221217`](https://pypi.org/project/trusspy/20221217/)

I got error below while running `https://github.com/adtzlr/trusspy/tree/master/tests/eADV_A_model_python.py`

> FileNotFoundError                         Traceback (most recent call last)
File [/opt/homebrew/lib/python3.11/site-packages/trusspy/model.py:418](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/trusspy/model.py:418), in Model.run(self)
    416 if self.logfile:
    417     sys.stdout = self.stdout
--> 418     sp_run(['pandoc', self.logfile_name+'.md', '-t', 'latex', '-o', self.logfile_name+'.pdf'])
    419     if self.Settings.logpdf: sp_run(['pandoc', self.logfile_name+'.md', '-t', 'html', '-s', '-o', self.logfile_name+'.html'])
File [/opt/homebrew/Cellar/python](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python)@3.11[/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py:548](https://file+.vscode-resource.vscode-cdn.net/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py:548), in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    545     kwargs['stdout'] = PIPE
...
   1900         err_msg = os.strerror(errno_num)
-> 1901     raise child_exception_type(errno_num, err_msg, err_filename)
   1902 raise child_exception_type(err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'pandoc'

Was wondering how to solve it. Any suggestion would be appreciated. Thank you so much!

**Comment by adtzlr** [comment]
Hi, you have to install pandoc.

```
pip install pandoc
```

**Comment by adtzlr** [comment]
I'll add it to the requirements.

**Comment by aaronsxzhao** [comment]
I have already downloaded 'pandoc' but the error was still there. Any suggestions? Thank you so much!

> Collecting pandoc
  Using cached pandoc-2.3-py3-none-any.whl
Requirement already satisfied: plumbum in /opt/homebrew/lib/python3.11/site-packages (from pandoc) (1.8.1)
Requirement already satisfied: ply in /opt/homebrew/lib/python3.11/site-packages (from pandoc) (3.11)
Installing collected packages: pandoc
Successfully installed pandoc-2.3

> FileNotFoundError: [Errno 2] No such file or directory: 'pandoc'

**Comment by adtzlr** [comment]
I'll have a look. In the meantime, you could also try to disable the log file.

`M = tp.Model(logfile=False)`

**Comment by adtzlr** [comment]
@aaronsxzhao, did my last comment solve your problem?

**Comment by aaronsxzhao** [comment]
yes thanks! it solved. Thanks again!
