### ISSUE TITLE
A0 and E0

### ISSUE THREAD

**Issue by saeedrastegarian** [adtzlr/trusspy#9]
Hi, I'd be grateful if you could help me figure out how should I assign A0 and E0, and generally, all variables which have been defined relatively when I use the excel sheet as inputs. Regards,
[truss1.xlsx](https://github.com/adtzlr/trusspy/files/4376368/truss1.xlsx)

**Comment by adtzlr** [comment]
Hi Saeed,

could you please provide a minimal (not-)working example? (or at least a minimal code snipped where your question arises) even a simple excel input file would be great so I can follow your question more easily.

Thanks in advance!

**Comment by saeedrastegarian** [comment]
> Hi Saeed,
> 
> could you please provide a minimal (not-)working example? (or at least a minimal code snipped where your question arises) even a simple excel input file would be great so I can follow your question more easily.
> 
> Thanks in advance!

done,tnx

**Comment by adtzlr** [comment]
That's indeed a bit confusing: I use TrussPy with absolute or relative values "as they are" without scaling the solution from a relative input variable to an absolute one. So you're right, there is no such option available for now. Thank you, will have a look on it!

**Comment by saeedrastegarian** [comment]
> That's indeed a bit confusing: I use TrussPy with absolute or relative values "as they are" without scaling the solution from a relative input variable to an absolute one. So you're right, there is no such option available for now. Thank you, will have a look on
